global:

  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bandwidth_scraper'

    scrape_interval: 5s

    static_configs:
      - targets: ['bw.dosdetection.de:2112']
      - targets: ['thresholds.dosdetection.de:2112']
      - targets: ['detection.dosdetection.de:2112']
