{
 "title": "Volume-based DoS Detection",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Peered Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Throughput (Mbps)" }
   ],
   "targets": [
    { "expr": "sum(bw)", "legendFormat": "Total" },
    {
     "expr": "bw{flow_direction=\"down\"}",
     "legendFormat": "Downstream"
    },
    {
     "expr": "bw{flow_direction=\"up\"}",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "DoS Alert",
   "type": "graph",
   "description": "Shows zero if the current bandwidth in the network is lower than the calculated threshold, else the measured throughput.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Throughput (Mpbs)" }
   ],
   "targets": [
    { "expr": "detection" }
   ]
  },
  {
   "title": "Calculated Thresholds",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "thresholds{hour=\"0\"}",
     "legendFormat": "00:00 - 00:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"1\"}",
     "legendFormat": "01:00 - 01:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"2\"}",
     "legendFormat": "02:00 - 02:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"3\"}",
     "legendFormat": "03:00 - 03:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"4\"}",
     "legendFormat": "04:00 - 04:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"5\"}",
     "legendFormat": "05:00 - 05:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"6\"}",
     "legendFormat": "06:00 - 06:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"7\"}",
     "legendFormat": "07:00 - 07:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"8\"}",
     "legendFormat": "08:00 - 08:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"9\"}",
     "legendFormat": "09:00 - 09:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"10\"}",
     "legendFormat": "10:00 - 10:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"11\"}",
     "legendFormat": "11:00 - 11:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"12\"}",
     "legendFormat": "12:00 - 12:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"13\"}",
     "legendFormat": "13:00 - 13:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"14\"}",
     "legendFormat": "14:00 - 14:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"15\"}",
     "legendFormat": "15:00 - 15:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"16\"}",
     "legendFormat": "16:00 - 16:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"17\"}",
     "legendFormat": "17:00 - 17:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"18\"}",
     "legendFormat": "18:00 - 18:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"19\"}",
     "legendFormat": "19:00 - 19:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"20\"}",
     "legendFormat": "20:00 - 20:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"21\"}",
     "legendFormat": "21:00 - 21:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"22\"}",
     "legendFormat": "22:00 - 22:59 Uhr"
    },
    {
     "expr": "thresholds{hour=\"23\"}",
     "legendFormat": "23:00 - 23:59 Uhr"
    }
   ]
  }
 ]
}